functions:
  itinerary_tool:
    _type: travel_itinerary

  flight_search:
    _type: flight_search

llms:
  nim_llm:
    _type: nim
    model_name: ${MODEL_NAME}
    base_url: ${NVIDIA_BASE_URL}
    api_key: ${NVIDIA_API_KEY}
    temperature: 0.7
    top_p: 0.9
    max_tokens: 2048

workflow:
  _type: react_agent
  llm_name: nim_llm
  tool_names: [flight_search, itinerary_tool]
  verbose: true
  handle_parsing_errors: true
  max_retries: 2

